# Generated by Django 5.1.6 on 2025-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_category_menuitem_remove_rental_bike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
