# Generated by Django 5.1.6 on 2025-05-11 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_deliveryaddress_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Promotion",
        ),
    ]
