# Generated by Django 5.1.6 on 2025-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_deliveryaddress_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
